fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
restart-strategy.type: fixed-delay
jobmanager.rpc.address: flink-jobmanager
sql-gateway.endpoint.rest.port: 8083
taskmanager.network.memory.max: 512mb
metrics.scope.task: flink.taskmanager.<tm_id>.<job_name>.<task_name>.<subtask_index>
metrics.scope.tm: flink.taskmanager.<tm_id>
s3.secret-key: minioadmin
taskmanager.network.memory.fraction: 0.1
parallelism.default: 2
cluster.evenly-spread-out-slots: true
state.backend.type: rocksdb
fs.s3a.secret.key: minioadmin
taskmanager.network.memory.min: 64mb
s3.path-style-access: true
taskmanager.memory.process.size: 2048m
execution.checkpointing.mode: EXACTLY_ONCE
metrics.reporter.prom.port: 9091
sql-gateway.session.max-num: 100
sql-gateway.endpoint.rest.address: 0.0.0.0
state.backend.incremental: true
web.cancel.enable: true
fs.s3a.path.style.access: true
security.ssl.internal.enabled: false
sql-gateway.session.idle-timeout: 30min
jobmanager.rpc.port: 6123
rest.bind-address: 0.0.0.0
execution.checkpointing.interval: 10s
execution.checkpointing.timeout: 60s
s3.access-key: minioadmin
rest.port: 8081
restart-strategy.fixed-delay.delay: 10s
web.submit.enable: true
rest.address: 0.0.0.0
akka.tcp.timeout: 60s
sql-gateway.session.check-interval: 10s
execution.checkpointing.max-concurrent-checkpoints: 1
blob.server.port: 6124
fs.s3a.access.key: minioadmin
state.checkpoints.num-retained: 3
metrics.system-resource: true
classloader.check-leaked-classloader: true
high-availability.type: NONE
metrics.system-resource-probing-interval: 5000
metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
state.savepoints.dir: s3a://flink/savepoints
query.server.port: 6125
jobmanager.bind-host: 0.0.0.0
s3.endpoint: http://minio:9000
taskmanager.numberOfTaskSlots: 2
metrics.scope.jm.job: flink.jobmanager.<job_name>
akka.ask.timeout: 60s
sql-client.execution.result-mode: table
taskmanager.network.memory.floating-buffers-per-gate: 8
taskmanager.bind-host: 0.0.0.0
classloader.resolve-order: child-first
metrics.scope.jm: flink.jobmanager
sql-client.execution.max-table-result.rows: 1000
restart-strategy.fixed-delay.attempts: 3
taskmanager.network.memory.buffers-per-channel: 2
jobmanager.memory.process.size: 1024m
metrics.scope.tm.job: flink.taskmanager.<tm_id>.<job_name>
security.ssl.rest.enabled: false
fs.s3a.connection.ssl.enabled: false
env.log.dir: /opt/flink/log
execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION
execution.checkpointing.min-pause: 5s
state.checkpoints.dir: s3a://flink/checkpoints
fs.s3a.endpoint: http://minio:9000
